### ISSUE TITLE
Random effect changes when interaction level numbering changes

### ISSUE THREAD

**Issue by yuexiao-marketingattribution** [JuliaStats/MixedModels.jl#529] opened 2021-06-01 15:18 UTC
Running the model spec below on the attached data.  I got the fixed effects in the table.

volume ~ 1 + covid_impact + base_price + ppi + covid_stringency_index & channel_type + trend & channel_type + (1 | channel_type_sub_brand) + ((0 + base_price) | channel_type_sub_brand) + ((0 + ppi) | channel_type_sub_brand)

![image](https://user-images.githubusercontent.com/29954116/120348097-78bc9180-c2c2-11eb-9d88-4a2b7aa904f6.png)

If I use channel_type_sub_brand_2, a different numbering from channel_type_sub_brand, I got slightly different fixed effect results despite the fact the data used in two models are exactly the same.
![image](https://user-images.githubusercontent.com/29954116/120348226-9b4eaa80-c2c2-11eb-838b-e32a4a8e21db.png)

[data_short.csv](https://github.com/JuliaStats/MixedModels.jl/files/6577276/data_short.csv)

**Comment by dmbates** [comment] 2021-06-07 22:31
Can you tell us how you represent `channel_type`, `channel_type_sub_brand`, etc.?  By default they will be read by `CSV.File` as `Int64`.  Did you convert them to Strings or PooledArrays of strings or CategoricalArrays?  I am unable to reproduce that coeftable and I'm not sure if it is because of the way I converted those columns.

I see that the fixed-effects model matrix is singular (the -0.0 estimates for the `channel_type: 0` interactions mean they aren't being estimated).  Is this expected?  Is there a reason to estimate the interaction terms and not a main effect for `channel_type`?

**Comment by yuexiao-marketingattribution** [comment] 2021-06-08 13:22
To be more precise - I was using Julia 1.1.1 and MixedModels 1.1.6 (Sorry a truly old version :=().  Here is the sequence I was testing this data - 

julia>model_ready_data_path = "/Users/Yue/Downloads/debug/julia_model_difference/data_short.csv"
julia>model_ready_data = CSV.read(model_ready_data_path)

julia>DataFrames.categorical!(model_ready_data, [:channel_type, :channel_type_sub_brand_2, :channel_type_sub_brand])
julia>weight_vector = convert(Vector{Float64}, model_ready_data[:, :observation_weight])

julia>modelform = @formula(volume ~ 1 + covid_impact + base_price + ppi + 
    covid_stringency_index & channel_type + trend & channel_type + 
    (1 | channel_type_sub_brand) + 
    ((0 + base_price) | channel_type_sub_brand) + 
    ((0 + ppi) | channel_type_sub_brand))

julia>MixedModels.NLopt.srand(123)
julia>model = MixedModels.LinearMixedModel(modelform, model_ready_data, weights=weight_vector)
julia>model.optsum.optimizer = :LN_PRAXIS
julia>model_fit = MixedModels.fit!(model)

MixedModels.NLopt.srand(123)
modelform = @formula(volume ~ 1 + covid_impact + base_price + ppi + 
    covid_stringency_index & channel_type + trend & channel_type + 
    (1 | channel_type_sub_brand_2) + 
    ((0 + base_price) | channel_type_sub_brand_2) + 
    ((0 + ppi) | channel_type_sub_brand_2))

model = MixedModels.LinearMixedModel(modelform, model_ready_data, weights=weight_vector)
model.optsum.optimizer = :LN_PRAXIS
model_fit = MixedModels.fit!(model)

We used the random seeds and set the optimizer to LN_PRAXIS a while ago as we noticed that the default setting has some random elements to it so results could change for different model runs.  This reminded me so that I tested removing the seed and optimizer setup.  Now the results look much closer(but different from either of the original results.). Differences in the last digit could almost certainly be attributed to rounding.

![image](https://user-images.githubusercontent.com/29954116/121191167-5500ca80-c831-11eb-8dc4-4d97873482eb.png)

I can't seem to identify any reference to optimizer any more in the current MixedModels code.  Do you recall efforts in the last 2 years to remove any potential randomness in the estimation process?

Thanks a lot!

**Comment by dmbates** [comment] 2021-06-08 17:26
Ah, the plot thickens!

There are several balls in the air here.  As you mentioned, you are using a very old version of the MixedModels package which may be causing other packages to be held at old versions too.  Also, you are using :LN_PRAXIS as the optimizer instead of the default :LN_BOBYQA.  PRAXIS seems to be affected by the call to NLopt.srand (I didn't even know it existed) but BOBYQA shouldn't be.  The main effect of using PRAXIS seems to be taking longer to converge.

Using the default optimizer and recent versions of the packages CSV, DataFrames, and MixedModels
```julia
(issue529) pkg> status
      Status `~/projects/issue529/Project.toml`
  [336ed68f] CSV v0.8.5
  [a93c6f00] DataFrames v1.1.1
  [ff71e718] MixedModels v4.0.0-DEV `https://github.com/JuliaStats/MixedModels.jl.git#main`
```
I can run the enclosed Pluto notebook and get reproducible results with BOBYQA but not with PRAXIS.
[notebook.txt](https://github.com/JuliaStats/MixedModels.jl/files/6618463/notebook.txt)

You should be able to take a copy of that file, change the extension to .jl, and run Julia in the directory.  Create a project with
```julia
using Pkg
Pkg.activate(".")
Pkg.add(["CSV","DataFrames", "Pluto"])
Pkg.add(url="https://github.com/JuliaStats/MixedModels.jl", rev="main")
using Pluto
Pluto.run()
```
and in the browser window select the notebook.jl file

If that seems like it is too involved then just run the code chunks (i.e. those that don't start with `md`) in the file.

**Comment by dmbates** [comment] 2021-06-08 17:51
Here is what running the Pluto notebook produces for me
[notebook.pdf](https://github.com/JuliaStats/MixedModels.jl/files/6618651/notebook.pdf)

**Comment by yuexiao-marketingattribution** [comment] 2021-06-08 18:51
Thanks a lot!  I will test what you suggested.  And, It's so nice to hear from you!

**Comment by dmbates** [comment] 2021-06-10 14:06
@yuexiao-marketingattribution Can we close this issue?

**Comment by yuexiao-marketingattribution** [comment] 2021-06-15 20:55
Reopen just to write some comments:  Why did we have slight different results with BOBYQA when the ordering of the levels changed?  The data is exactly the same

**Comment by dmbates** [comment] 2021-06-19 15:16
A favorite aphorism for me is "In theory, theory and practice are the same.  In practice, they're not."

In mathematical theory addition is associative so you should get the same sum from a set of numbers no matter what order you add them in.  In practice, using floating point arithmetic, that isn't the case - because of round off.  This means that if you reorder the columns in a matrix, which is what will happen in this case, matrix products that should, in theory be identical, aren't.  This is why using different accelerated versions of the BLAS (Basic Linear Algebra Subroutines) like MKL (Intel's Math Kernel Library) versus OpenBLAS (the default for Julia) versus the Fortran reference BLAS (which, I believe, is the still the default in R) will produce slightly different answers because they spread the calculations over different cores in different ways.

Given the nature of the optimization here and the fact that the deviance surface is very flat, it is not surprising that small differences in the evaluation of the deviance lead to slightly different values of the optimum.

**Closed** 2021-06-21 13:59 UTC
